.TH sedcli 8
.SH NAME
sedcli \- manage Opal Self-Encrypting Drives (SEDs) NVMe SSDs

.SH SYNOPSIS

\fBsedcli\fR <command> [options...]

.SH DESCRIPTION
Sedcli enables a system Administrator/Operator to manage NVMe SEDs that are TCG
Opal compliant. In Opal terminology SED is called a Trusted Peripheral (TPer)
and provides an Admin Security Provider (Admin SP) and Locking Security Provider
(Locking SP).

.PP
Management of the TCG Opal features require several operations that are performed
as an Administrator within the TCG Opal command set to either the AdminSP or
LockingSP. The AdminSP provides commands that enable the user to perform
administrative operations such as taking ownership of the device, activation of
the LockingSP, and revert the TPer, whereas the LockingSP provides commands that
enable the user to configure and enable locking enforcement on user data either
globally or on a locking range basis after the LockingSP has been activated by
the AdminSP.

.PP
To start Opal management, an Administrator typically needs to perform the
following process at a minimum:
.IP
1. Take ownership of the device (setting a non-MSID credential for the SID
Authority in the AdminSP)
.IP
2. Activate the LockingSP (this will move the Opal feature to the Manufactured
state and copy the SID authority password to the LockingSP Admin1 password)
.IP
3. Enable Read Lock Enabled and Write Lock Enabled on all desired ranges
(e.g. Global Range)
.PP
After these steps are accomplished, the TPer will be Read or Write locked after
power cycle or when explicitly locked using sedcli command.

.PP
In addition to these basic flows, one can perform crypto erase of the TPer
using the SID authority or the PSID authority as part of revert TPer operation.
In case of using the PSID authority the operator needs to provide the credential
that is printed on the disk label. The Revert TPer operation reverts device
back to the Manufactured-Inactive state, which then requires re-configuration
of the Opal management system using the process previously identified (i.e.
take ownership, activate LSP, enable global range). It is also possible to
update Admin1 password for Locking SP.

.SH OPTIONS

.TP
\fB\-D -d <device> [-f {normal|udev}]\fR
.TQ
\fB\-\-discovery --device <device> [--format {normal|udev}]\fR
Performs Level 0 and Level 1 Discovery and prints out the info in human-readable(default) or
machine friendly format.

.TP
\fB\-O -d <device> [-k <pwd-opts>]\fR
.TQ
\fB\-\-ownership --device <device> [--key-source <pwd-opts>]\fR
Takes ownership of the device.

.TP
\fB\-A -d <device> [-k <pwd-opts>]\fR
.TQ
\fB\-\-activate-lsp --device <device> [--key-source <pwd-opts>]\fR
Activates Locking SP.

.TP
\fB\-R -d <device> [-i] [-n] [-k <pwd-opts>]\fR
.TQ
\fB\-\-revert --device <device> [--psid] [--non-destructive] [--key-source <pwd-opts>]\fR
Performs Destructive or Non-Destructive Revert TPer to Manufactured-Inactivate
state using either SID or PSID authority.

.TP
\fB\-S -d <device> [-k <pwd-opts>]\fR
.TQ
\fB\-\-setup-global-range --device <device> [--key-source <pwd-opts>]\fR
Sets Read Lock Enabled (RLE) and Write Lock Enabled (WLE) bis for global locking
range. This effectively enables locking of all user data. Locking will start
after power cycle or when explicitly locked using \fb\-\-lock-unlock\fR command.

.TP
\fB\-L -d <device> -t <accesstype> [-k <pwd-opts>]\fR
.TQ
\fB\-\-lock-unlock --device <device> --accesstype {RO|RW|LK} [--key-source <pwd-opts>]\fR
.IP
Changes the lock state for the device. Following access modes are available:
.IP
1. Read-Only(RO) - user can only read the data from the disk.
.IP
2. Read-Write(RW) - user can read/write data from/to the disk.
.IP
3. Locked(LK) - data is locked, user can NOT read/write data from/to the disk.

.TP
\fB\-P -d <device> [-k <new-pwd-opts>] [-o <old-pwd-opts>]\fR
.TQ
\fB\-\-set-password --device <device> [--key-source <new-pwd-opts>] [--old-key-source <old-pwd-opts>]\fR
Updates password for Admin1 authority in Locking SP.

.TP
\fB\-M -d <device> [-e {TRUE|FALSE}] [-m {TRUE|FALSE}] [-k <pwd-opts>]\fR
.TQ
\fB\-\-mbr-control --device <device> [--enable {TRUE|FALSE}] [--done {TRUE|FALSE}] [--key-source <pwd-opts>]\fR
.IP
Enable/Disable MBR Shadow and/or Set/Unset MBR Done.
MBR Done update to TRUE will only take effect when MBR Shadow is enabled.

.TP
\fB\-W -d <device> -f <pba_file> [-o <offset>] [-k <pwd-opts>]\fR
.TQ
\fB\-\-write-mbr --device <device> --file <pba_file> [--offset <offset>] [--key-source <pwd-opts>]\fR
Write data into MBR shadow region(MBR table).
MBR shadow should be enabled for the PBA to take effect.

.TP
\fB\-B -d <device> -r {1|0}\fR
.TQ
\fB\-\-block_sid --device <device> --hwreset {1|0}\fR
Issue BlockSID authentication command with Clear Event flag via --hwreset option.

.TP
\fB\-V\fR
.TQ
\fB\-\-version\fR
Prints version of sedcli.

.TP
\fB\-H\fR
.TQ
\fB\-\-help\fR
.br
Prints global help on available commands and usage

.IP "To print command specific help use following syntax:"
.IP "\fBsedcli <command> -H\fR or \fBsedcli <command> --help\fR"
.IP "For example:"
.IP "\fBsedcli -D -H\fR or \fBsedcli --discovery --help\fR"

.SH COMMON OPTIONS

.IP "\fB\-q\fR or \fB\-\-quiet\fR"
Suppress informative messages, specifically the "Success" message.

.IP "\fB\-p\fR or \fB\-\-pass-thru\fR"
Force use of NVMe pass-through interface, even if Linux OPAL Driver is configured.

.SH PASSWORD OPTIONS

Commands that require one or more passwords may specify the source for
those passwords (the key source). The following source options are available:
.P
1. \fBuser\fR - prompt the user on stdio for the passwords.
This is the default behavior.

.SH COPYRIGHT
Copyright(c) 2018-2020 by the Intel Corporation.

.SH AUTHOR
This manual page was created by Andrzej Jakowski <andrzej.jakowski@intel.com>

.SH SEE ALSO
.TP
sedcli(8)
